rules:
  - id: node-jwt-weak-default
    message: Remove weak default for JWT secret and require explicit config.
    severity: ERROR
    languages: [javascript, typescript]
    pattern: |
      const $X = process.env.JWT_SECRET?.trim() || "changeme";
    fix: |
      const $X = process.env.JWT_SECRET?.trim();

  - id: node-jwt-weak-default-var
    message: Remove weak default for JWT secret and require explicit config.
    severity: ERROR
    languages: [javascript, typescript]
    pattern: |
      const $X = process.env["JWT_SECRET"]?.trim() || "changeme";
    fix: |
      const $X = process.env["JWT_SECRET"]?.trim();

  - id: env-jwt-secret-changeme
    message: JWT_SECRET must not be "changeme" in .env files.
    severity: ERROR
    languages: [generic]
    paths:
      include:
        - "**/.env*"
    pattern: |
      JWT_SECRET=changeme
    fix: |
      # JWT_SECRET=<set-strong-secret-here>
