services:
  # Database
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pg}
      POSTGRES_USER: pg
      POSTGRES_DB: wt
    ports: ["5434:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Object Storage
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  svc-auth:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-auth
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3001
      HOST: 0.0.0.0
    ports: ["3001:3001"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Catalog Service
  svc-catalog:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-catalog
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3002
      HOST: 0.0.0.0
    ports: ["3002:3002"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Enquiries Service
  svc-enquiries:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-enquiries
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3003
      HOST: 0.0.0.0
    ports: ["3003:3003"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3003/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Billing Service
  svc-billing:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-billing
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3004
      HOST: 0.0.0.0
    ports: ["3004:3004"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3004/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Vendors Service
  svc-vendors:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-vendors
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3005
      HOST: 0.0.0.0
    ports: ["3005:3005"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3005/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Guests Service
  svc-guests:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-guests
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3006
      HOST: 0.0.0.0
    ports: ["3006:3006"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3006/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Payments Service
  svc-payments:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: svc-payments
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      PORT: 3007
      HOST: 0.0.0.0
    ports: ["3007:3007"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3007/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Frontend (Next.js)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      DATABASE_URL: postgresql://pg:${DB_PASSWORD:-pg}@db:5432/wt
      INTERNAL_API_URL: http://host.docker.internal
      PORT: 3000
      HOST: 0.0.0.0
    ports: ["3000:3000"]
    depends_on:
      svc-auth:
        condition: service_healthy
      svc-catalog:
        condition: service_healthy
      svc-enquiries:
        condition: service_healthy
      svc-billing:
        condition: service_healthy
      svc-vendors:
        condition: service_healthy
      svc-guests:
        condition: service_healthy
      svc-payments:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  minio_data:
