spec:
  name: weddingtech
  services:
    - name: svc-auth
      source_dir: apps/svc-auth
      http_port: 3000
    - name: svc-catalog
      source_dir: apps/svc-catalog
      http_port: 3000
    - name: svc-enquiries
      source_dir: apps/svc-enquiries
      http_port: 3000
    - name: svc-billing
      source_dir: apps/svc-billing
      http_port: 3004
