name: weddingtech
region: fra

services:
  - name: web
    github:
      repo: olegin77/wed
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    source_dir: apps/svc-website
    http_port: 3000
    envs:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3000"
    build_command: |
      corepack enable
      corepack prepare pnpm@9.12.0 --activate
      cd ../..
      pnpm -w install --frozen-lockfile
      cd apps/svc-website
      pnpm build
    run_command: pnpm start
