name: Apply PR suggestions
on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  contents: write

jobs:
  apply:
    if: >
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge all GitHub suggestions on this PR
        uses: tianhaoz95/merge-github-suggestions@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.issue.number }}
