name: Autofix (Semgrep + ESLint)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps (root)
        run: pnpm install --ignore-scripts || true

      - name: ESLint --fix (workspace)
        run: pnpm -w -r --if-present run lint:fix || true

      - name: Install Semgrep
        run: python -m pip install --upgrade pip semgrep

      - name: Semgrep --fix
        run: semgrep --config .semgrep.yml --fix || true

      - name: Commit autofixes (if any)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "${GIT_AUTHOR_NAME}"
            git config user.email "${GIT_AUTHOR_EMAIL}"
            git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${HEAD_REPO}.git"
            git add -A
            git commit -m "chore: autofix (eslint + semgrep)"
            git push origin HEAD:${HEAD_REF}
          else
            echo "No autofixes needed."
          fi
