name: CI

on:
  push:
    branches: [main, codex]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm CLI
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Setup Node + pnpm cache
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Setup Node (no cache)
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify pnpm availability
        run: pnpm -v

      - name: Install workspace dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            # The monorepo intentionally omits a lockfile in some setups; fall back to a standard install.
            pnpm install
          fi

      # ---- FIX: запускаем корневой скрипт, внутри которого уже безопасный рекурсивный линт ----
      - name: Lint (workspace via root script)
        run: pnpm run lint

      - name: Test (workspace recursive)
        run: pnpm -w -r run test --if-present

      - name: Build (workspace recursive)
        run: pnpm -w -r run build --if-present
