name: DO App Spec Lint
on:
  push:
    branches: [ codex ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PyYAML
        run: pip install pyyaml
      - name: Validate YAML
        run: python - <<'PY'
import yaml
with open('infra/do/app.yaml','r',encoding='utf-8') as f:
    yaml.safe_load(f)
print("app.yaml OK")
PY
