name: DO Deploy (manual)
on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'DigitalOcean App ID'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          APP_ID: ${{ github.event.inputs.app_id }}
        run: |
          set -e
          curl -sS -X POST \
            -H "Authorization: Bearer ${DO_API_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://api.digitalocean.com/v2/apps/${APP_ID}/deployments" \
            -d '{}'
